### ISSUE TITLE
CSV-W mapping: enumerate measure types

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#127]
When using a measure dimension and `Measure Type` column, the set of measure types needs to be explicitly listed in the mapping file, e.g.:

```
      "Measure Type": {
        "dimension": "http://purl.org/linked-data/cube#measureType",
        "value": "http://gss-data.org.uk/def/measure/{measure_type}",
        "types": ["net-mass", "volume"]
      }
```

The `"types"` key lists the allowed values for this `"Measure Type"` column.

If `"types"` isn't provided, we should default to searching through the CSV file for all the distinct values, see e.g. https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/csvw/t2q.py#L64

**Comment by canwaf** [comment]
This has been implemented in csvcubed. https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#Measures%20and%20Units
