### ISSUE TITLE
Catch errors for scraper Markdown preview

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#128]
the scraper markdown preview will currently throw an error if an expected attribute is missing.

we need to update so it catches the error and just lets the DE know if eg mediaType is missing, so (where viable) they can adapt the script without needing to update and redeploy gssutils to compensate.

this: https://github.com/GSS-Cogs/gss-utils/blob/7ec4fe7cd00c3dcea127ef9b28eefd85f1e146d9/gssutils/scrape.py#L101

**Comment by ajtucker** [comment]
I know you said you'd added this issue, @mikeAdamss , but somehow I missed it when I created #129  :(

Meanwhile, I've added a PR.
