### ISSUE TITLE
Global/Family level Codelist URIs are different to Dataset Level URIs

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/gss-utils#137]
Look in to why there are inconsistent conventions applied here, make a decision on which one we should use and migrate the losers over to the winner's convention.

| Level | Concept Scheme Root URI | Concept URI |
| :-- | :-- | :--: |
| Global | http://gss-data.org.uk/def/concept-scheme/my-favourite-code-list | http://gss-data.org.uk/def/concept-scheme/my-favourite-code-list/{notation} |
| Family | http://gss-data.org.uk/def/my-favourite-family/concept-scheme/my-favourite-code-list | http://gss-data.org.uk/def/my-favourite-family/concept-scheme/my-favourite-code-list/{notation} |
| Dataset | http://gss-data.org.uk/data/gss_data/my-favourite-family/the-best-dataset-ever#scheme/my-favourite-code-list | http://gss-data.org.uk/data/gss_data/my-favourite-family/the-best-dataset-ever#concept/my-favourite-code-list/{notation} |

**Comment by rossbowen** [comment]
I wrote this a while back:

|                           |               |                                                                                         |
|---------------------------|---------------|-----------------------------------------------------------------------------------------|
| Data Cube                 |               | `gss-data.org.uk/data/{dataset-name}`                                                   |
| Data Structure Definition |               | `gss-data.org.uk/data/{dataset-name}/structure`                                         |
| Component                 |               | `gss-data.org.uk/data/{dataset-name}/component`                                         |
| Dimension                 | Global        | `gss-data.org.uk/def/dimension/{dimension-name}`                                        |
| Dimension                 | Within-family | `gss-data.org.uk/def/dimension/{family-name}/{dimension-name}`                          |
| Dimension                 | Local         | `gss-data.org.uk/data/{dataset-name}/dimension/{dimension-name}`                        |
| Measure                   | Global        | `gss-data.org.uk/def/measure/{measure-name}`                                            |
| Measure                   | Within-family | `gss-data.org.uk/def/measure/{family-name}/{measure-name}`                              |
| Measure                   | Local         | `gss-data.org.uk/data/{dataset-name}/measure/{measure-name}`                            |
| Attribute                 | Global        | `gss-data.org.uk/def/attribute/{attribute-name}`                                        |
| Attribute                 | Within-family | `gss-data.org.uk/def/attribute/{family-name}/{attribute-name}`                          |
| Attribute                 | Local         | `gss-data.org.uk/data/{dataset-name}/attribute/{attribute-name}`                        |
| Codelist                  | Global        | `gss-data.org.uk/def/concept-scheme/{codelist-name}`                                    |
| Codelist                  | Within-family | `gss-data.org.uk/def/concept-scheme/{family-name}/{codelist-name}`                      |
| Codelist                  | Local         | `gss-data.org.uk/data/{dataset-name}/concept-scheme/{codelist-name}`                    |
| Concept                   | Global        | `gss-data.org.uk/def/concept/{concept-name}`                                            |
| Concept                   | Within-family | `gss-data.org.uk/def/concept/{family-name}/{concept-name}`                              |
| Concept                   | Local         | `gss-data.org.uk/data/{dataset-name}/concept/{concept-name}`                            |
| Observation               |               | `gss-data.org.uk/data/{dataset-name}/obs/{component-1}/{component-2}/.../{component-n}` |

**Comment by canwaf** [comment]
We will be addressing this in gss-cogs/csvcubed#44 when someone takes this spike ticket up, @rossbowen. You will be consulted on the URI/namespaces used.
