### ISSUE TITLE
Remove incorrect uses of dcat:Dataset from Data-set CSV-W Generation

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/gss-utils#149]
The code in gss-utils which is used to generate the PMDCAT and DCAT metadata necessary to insert the `qb:DataSet` into the right catalogue on PMD is setting some unusual types.

In the below image, there are multiple nodes which have the `dcat:Dataset` type. The only node which should have this is the `ofgemCheapestTarrifs:-catalog-entry` node. 

Alter the code so it doesn't generate the incorrect `dcat:Dataset` predicates.

See https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=53844830 for some documentation on the PMDCAT/DCAT metadata required.

![image](https://user-images.githubusercontent.com/73846016/105340918-688afc00-5bd6-11eb-87d6-73d8f27a9dbb.png)

**Comment by ajtucker** [comment]
Well spotted!

The offending line looks to be https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/csvw/dsd.py#L67.

Based on https://github.com/Swirrl/cogs-issues/wiki/PMD4-metadata, the types of this should be `qb:DataSet` and `pmdcat:DataCube`.

Note that it isn't necessarily "wrong" to call a `qb:DataSet` a `dcat:Dataset`, but I do agree with your interpretation of DCAT and dataset distributions. As we refine our understanding and models, we need to add axioms to our ontology to help us keep track of these constraints, e.g. that `dcat:Dataset` is disjoint with `qb:DataSet`.
