### ISSUE TITLE
Set dcat:theme

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/gss-utils#169]
Can we take the family from the `info.json` and implement a way in `gssutils` to implement this in the RDF output.

When BAs create the entry in Airtable, they specify the family which then appears in an `info.json`. This should be utilised rather than setting the theme manually in the transforms.

```json
    "families": [
        "Some Family", "Another Family"
    ],
```

Should produce RDF of the form:

```turtle
<http://gss-data.org.uk/data/my-dataset> dcat:theme 
    <http://gss-data.org.uk/def/gdp#some-family>, <http://gss-data.org.uk/def/gdp#another-family> .
  
```

Edit: the related PR handles this for a single family (it extracts the first from the `info.json` but the ideal solution would be able to handle multiple listed families.

**Comment by mikeAdamss** [comment]
@rossbowen - I've implemented the above in a PR, but just noticed this is also tagged to multi-family datasets, which it won't do (not sure we can do those at all right now). That's either a different task or this is a lot more complex that we thought.

**Comment by rossbowen** [comment]
Thanks @mikeAdamss!

I think the initial pull is a start though setting multiple themes should be in scope. Once we review the initial pull we can move this back and maybe someone will be able to pick it up - but thanks for the quick win.

**Comment by ajtucker** [comment]
I've tried to capture the remaining issues in #174, so guess we can close this again?
