### ISSUE TITLE
bug: Cubes, storing scraper pointer not object

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#179]
this line: https://github.com/GSS-Cogs/gss-utils/blob/47ccba0c554c70ef0beff0024fb900b098966f49/gssutils/transform/cubes.py#L88

is storing a pointer to the scraper metadata rather than snapshotting it at the time of creation.

I _think_ this has a knock on effect where you can pass a `scraper` to a cube and then change it later in the main script. This is leading to some confusing behaviour when used with certain patterns.

should be a trivial fix, i.e use deepcopy.

**Comment by mikeAdamss** [comment]
fixed in passing (once this branch gets merged): https://github.com/GSS-Cogs/gss-utils/blob/b505b7cf705a4ddf434be6eb9fa209acbbd0927a/gssutils/transform/cubes/cubes.py#L203

**Comment by canwaf** [comment]
Cubes are no longer handled by gss-utils.
