### ISSUE TITLE
Cubes getcwd() straggler

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#180]
In re-factoring cubes.py the other day to use the `id` key, if available, from `info.json`, I missed an `os.getcwd()`.

It's causing a dodgy error message, e.g. https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC-RTS-Small-area/125/console

**Comment by canwaf** [comment]
Cubes are no longer handled by gss-utils but by csvcubed.
