### ISSUE TITLE
Use content-api for gov.uk

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#20]
The gov.uk scraper currently gathers metadata from the templated web pages on gov.uk.

There is a way to fetch some of this metadata in a more structured and machine-readable way via the [gov-uk-content-api](https://content-api.publishing.service.gov.uk/#gov-uk-content-api).

Given a gov.uk web page, we can determine the path to get JSON from the content-api and traverse that instead. The issues with this approach are that the information about links to publications is still represented as HTML in the JSON.

However, this appears to be a better way to get at the metadata and will help GSS-Cogs/family-affordable-housing#12 where we want to get at the "live data tables" data.

**Comment by ajtucker** [comment]
Currently working on this in the https://github.com/GSS-Cogs/gss-utils/tree/use-govuk-content-api branch.

**Comment by ajtucker** [comment]
The new scraper works for the old scenarios, but not yet for the Live Tables page, which appears to have a different HTML layout.

**Comment by ajtucker** [comment]
Next steps:

[ ] - Merge into master and replace old gov.uk scraper, checking that it works ok for existing pipelines.
[ ] - Put Live Tables parsing on hold depending until we can get a grip on whether we can just do things manually for now.

**Comment by IeuanMan** [comment]
Set up conversation with data.gov

**Comment by ajtucker** [comment]
Tests passing. Also tested on current datasets.
