### ISSUE TITLE
pmdcat:DataCube not expanding correctly

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/gss-utils#203]
Using `pmdcat` as a compact URI in JSON-LD does not expand without placing `pmdcat` in the `@context`. This results in triples such as 

```ttl
<http://gss-data.org.uk/data/trade/some-data#dataset> a <pmdcat:DataCube> .
```

appearing in our output.

https://github.com/GSS-Cogs/gss-utils/blob/734a6b1876a06bd5bc79e9f50a131a4235be58c9/gssutils/csvw/dsd.py#L67

Rather than placing in the `@context`, I prefer providing a fully qualified PMD DataCube URI, `http://publishmydata.com/pmdcat#DataCube`.

**Comment by ajtucker** [comment]
See also https://github.com/GSS-Cogs/gss-utils/pull/171#issue-566755648
