### ISSUE TITLE
Add caching option to as_pandas() for Big Data access

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/gss-utils#226]
Add an option to cache the responses for as_pandas() data frame access for Odata rips, and to keep the data on machine for n days to speed up running and debugging fo pipelines.

Will help @GSS-Cogs/data-engineers build the pipeline.

**Comment by MartynBSpooner** [comment]
Not a mandatory requirement but you might be able to investigate utilising checksums to minimise file size storage on the drives.

**Comment by canwaf** [comment]
Any implementation of this should exist outside of gss-utils.
