### ISSUE TITLE
better temp scraper exception

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#240]
this line https://github.com/GSS-Cogs/gss-utils/blob/49e8e57d7398aa32c3f567c73dd08ab119817a20/gssutils/scrape.py#L287

assumes the dictionary key exists (which it might not) and a KeyError is not massively helpful to a DE user. Change it to check if said key does exist and raise something a big more useful if it doesn't, eg `We need a {thing} field to use a temp scraper, your info.json doesn't have one.`

**Comment by mikeAdamss** [comment]
@CharlesRendle - no expectations (no idea if you'll be done with WITHIN this sprint). But this is a nice little task if you need a sanity break between databaker-within and databaker-exceptions tasks.

Probably will need a few tests though, cant remember if the temp scraper has them (was quick and nasty) and if not it should.

**Comment by canwaf** [comment]
Should we fix this one, @mikeAdamss?

**Comment by mikeAdamss** [comment]
we should yes, but it's a minor thing, I was panning on using it for a freshly onboarded and/or student resource/person, so low priority, "nice to have:.
