### ISSUE TITLE
Suppress catalog and qb:DataStructureDefinition for multi-cube uploads

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/gss-utils#247]
Due to the size of CSV-Ws for family-trade/issue9, we need multiple CSV-Ws generated and follow the multi-graph paradigm without accretive upload. This involves specifying at `Cube().add_cube()` a flag which suppresses the generation of CSV-W catalog and qb:DSD for additional 'chunks' beyond the primary graph (i.e. the secondary graphs).

- [ ] add flag to `add_cube()` method & pass through to CSVWMapper
- [ ] suppress DSD and catalog generation with on new flag being true
- [ ] Add behave test to ensure DSD and trig not output when requested

**Comment by ajtucker** [comment]
The [CSV2RDF specification](https://www.w3.org/TR/csv2rdf/) offers up two modes of operation: minimal and standard.

[Swirrl's implementation](https://github.com/Swirrl/csv2rdf) adds another mode, annotated, which we're using to carry across the extra JSON-LD metadata in the `-metadata.json` file into the resulting triples.

We should be able to split out the metadata from the observations by taking advantage of this.
