### ISSUE TITLE
gssutils assumes attribute properties point to URIs

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/gss-utils#253]
Sometimes we want an attribute property to produce triples which point at literals, e.g.

```ttl
<obs> <#attribute> 10 .
```

A natural way to express this in our `info.json` might be:

```json
"Example" : {
    "attribute": "http://example.org/attribute"
}
```

i.e., omit a `valueUrl` from appearing in the CSVW output.

This code will need some altering:

https://github.com/GSS-Cogs/gss-utils/blob/972f7fc3930dfaeb395236649b6fcb8f1f01afa5/gssutils/csvw/mapping.py#L334

**Comment by Shannon95** [comment]
Pull request approved and needs merging into master.
