### ISSUE TITLE
view contents of scraper

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#283]
Add an optional switch to have gssutils log out metadata contents of scraper as json (so DE's can see a summary of whats actually getting scraped/what fields they can filter on etc).

**Comment by ajtucker** [comment]
This was the intention behind providing some `_repr_markdown_(self)` methods, so that the DE can display the scraper, collection, datasets and distributions and figure out how to filter things to get what they need.

**Comment by mikeAdamss** [comment]
gonna close this, in hindsight Alex has a point
