### ISSUE TITLE
decouple scrapers in gssutils

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#294]
There's an old (valid at the time) assumption that all metadata used by gssutils comes from a scraper.

**Construction Wrappers**

_Not bothered on the names particularly, but if we establish this pattern of using constructors for creating metadata its trivial to add more for future/differing use cases_.

- [ ] create metadata from a scraper
- [ ] create metadata from a json (the old "temp scrape")
- [ ] a user can create a Metadata() object inline via code.

**Ideally**
You'd want scraping to be an external component that acts upon a `Metadata` class. That's the much neater solution but possible a lot of work, so I'd consider than "nice to have" rather than a requirement for this task.

**ACCEPTANCE CRITERIA**

This task is done when:
- [ ] Constructors for all scenarios listed under "Construction Wrappers" all work.
- [ ] There's one or more BDD tests for each of those wrappers.

**Comment by mikeAdamss** [comment]
passing thought, construction via a class method is probably a nicer solution that just having imported functions floating around, so `Metadata.from_scraper(seed="info.json")` etc

**Comment by canwaf** [comment]
We should probably have a larger discussion about the architecture of gss-utils, and what should be contained therein. Should it just be a fast way to import a bunch of other utilities, which are actually developed elsewhere?

I'd think thank our scrapers should exist outside of gss-utils, similar to how databaker already exists outside of it. gss-utils will give us a great environment to behaviour test the integration of scrapers providing metadata to old-school csvw/trig generation and new way csvw generation via csvwlib.

This decoupling should be stronger, and the scrapers should find themselves outside of gss-utils entirely AFAIC.

**Comment by mikeAdamss** [comment]
gssutils is a metadata model (basically dcat, more or less).
the scrapers use that data model.

So I guess the key difference vs an external library like databaker is that databaker has standalone functionality whereas you'd never use the scrapers (a thing that populates the gssutils data model) without the gssutils data model.

Not opposed to more decoupling at all btw (I still think we should had just decoupled what we have before building anything new) but this task was more aiming to walk before we run.

I'll edit the task to more generic while I'm here, disagree with my own initial approach already :smile:

**Comment by canwaf** [comment]
Hrm, that's a better way of looking at it. Maybe the future state of gss-utils is scrapers + a databaker import + csvwlib import. What else would it need?

**Comment by ajtucker** [comment]
We could do with a chat around a whiteboard!

The metadata is currently bound up with the scraper singleton s.t. you start by creating the scraper object, use it to derive the metadata (as separate objects of a core Metadata class) and then reach those metadata objects from the scraper object, as in `scraper.dataset.title` etc.

While I agree it's good to modularise to the extent that we could `pip install metadata.dcat` and friends and depend on them, or expect that `csvwlib` has more tightly coupled classes, the thing I'd like to do first is to abstract the scrapers themselves s.t. we can have more of a plugin architecture.

Now that we've done a few and the interface has settled a bit, it makes sense to pull on these threads a little and create either an abstract class or interface that each scraper can inherit from.

Note that the scrapers will still need to be closely coupled to the metadata in the sense that any changes to the innards of metadata, e.g. deciding to use `rdfs:comment` differently to `dct:description` will require changes in every scraper. This is fine and expected.
