### ISSUE TITLE
Add qb:order to components

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#303]
The Data Cube vocab allows for ordering of components to give a hint to the user interface on how to display things, see https://www.w3.org/TR/vocab-data-cube/#attachment-example

By default, we should provide the order given by the columns in the Tidy CSV.

**Comment by Robsteranium** [comment]
NB: `qb:order` is about the order of the `qb:ComponentSpecification`s not the `qb:ComponentProperty`s (dimensions etc) themselves.

**Comment by ajtucker** [comment]
@Robsteranium , does PMD already support `qb:order` and if not, is there an issue we can link to?

**Comment by ajtucker** [comment]
Ooof, just spotted https://github.com/GSS-Cogs/GDP-vocabs/pull/1 !

**Comment by ajtucker** [comment]
Note that `csv2rdf` surprisingly turns e.g. `"qb:order": 1` into `qb:order "1"^^xsd:long` rather than `qb:order 1` as I'd expect.

See Swirrl/csv2rdf#63
