### ISSUE TITLE
Markdown literals

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#308]
Currently, we have `pmdcat:markdownDescription` whose range is a literal of type `<https://www.w3.org/ns/iana/media-types/text/markdown#Resource>`.

We'd previously proposed just using `dct:description` and allowing the data type to determine how it is rendered.

Ultimately, we need to decide what we want the publisher to include in `dct:description` and whether we need a separate property for markdown specific descriptions.

**Comment by canwaf** [comment]
From a csvwlib standpoint just assigning a data_type to the description literal would provide us what we need. Right now we're assuming that descriptions are always string literals (i.e. `xs:string`).

My preference is to use description and tell the user what dtype of description it is. Markdown is pretty readable from the word go.

**Comment by canwaf** [comment]
The implementation of markdown literals will be released soon. This will allow the inclusion of markdown in the description field as is, not requiring the use of `pmdcat:markdownDescription`. 

https://github.com/GSS-Cogs/csvcubed/issues/411 for further info.
