### ISSUE TITLE
Generate a standardised output_uri_template for existing qb units and measures

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/gss-utils#314]
Given existing qb units and measures which look the same, can we create/infer a standardised ouput_uri_template so that this isn't something which needs to be provided for every existing unit and measure.

**Comment by canwaf** [comment]
With the fixing of [this csvcubed bug](https://github.com/GSS-Cogs/csvcubed/issues/490), it will be very easy to generate output_uri_templates from existing units and measures.
