### ISSUE TITLE
XLSX Distributions appearing as openXML

### ISSUE THREAD

**Issue by RedWalters** [GSS-Cogs/gss-utils#35]
Some Distributions are being read in as media type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` which stops the spreadsheet being read in as as_pandas.

Eg: 

 - Input:
```
scraper = Scraper('https://www.gov.uk/government/statistical-data-sets/live-tables-on-affordable-housing-supply')
dist = scraper.distribution(title=lambda x: x.startswith('Table 1011'))
df = dist.as_pandas(sheet_name = 'data')
```

 - Output:
`FormatError: Unable to load application/vnd.openxmlformats-officedocument.spreadsheetml.sheet into Pandas DataFrame.
`

The current fix for this is adding `dist.mediaType = Excel` which forces the distribution to be read as an Excel file rather than using the given mediaType.

**Comment by mikeAdamss** [comment]
fixed by: https://github.com/GSS-Cogs/gss-utils/commit/f9a34c444d6aaef23e34d35c4dde98af22e6d32d
