### ISSUE TITLE
Rip Out Tracing

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#361]
this: https://github.com/GSS-Cogs/gss-utils/tree/master/gssutils/tracing

is a 2 year old spike/experiment around maintaining a record around where/how subsets of data from multiple sources combine to create a new output. At the time there was a requirement for BAs to understand what had happened in a transform in a human readable way (i.e how did subsets of 3 inputs becomes one output?).

That not an issue anymore, also, this never went beyond spike (and the code makes me wince a fair bit tbh) so it would be _really_ good to rip this out. 

I believe we've stopped using it completely now, but if needed we can replace with empty methods and depreciation warnings.

**Comment by mikeAdamss** [comment]
I would think there is _probably_ a provenance discussion that needs to happen, but if so I'd consider that in a separate/new issue.

**Comment by mikeAdamss** [comment]
covered in: https://github.com/GSS-Cogs/gss-utils/issues/362

**Comment by canwaf** [comment]
I suggest with anything we rip out that isn't required in future state gets a tombstoned warning (depreciation warning for stuff that is merely way out), and everything we're ripping out that would break a pipeline gets a critical error (saying it needs to be rewritten to fix.)
