### ISSUE TITLE
Test transforms

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#4]
It would be good to run existing transforms as a way to check that gss-utils hasn't broken anything and that the scrapers work ok.

This should probably be separate to the existing tests, as we don't want to fail because a transform isn't working. We'd just want to show up any potential issues.

**Comment by ajtucker** [comment]
@mikeAdamss has done some great work on this.

**Comment by mikeAdamss** [comment]
de prioritised in favour of some work on validation tooling, as that's getting painful.
