### ISSUE TITLE
Update Pandas to v1

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#48]
Pandas v1 release broke some tests, so it is pinned to 0.25.3, pending fixes.

**Comment by ajtucker** [comment]
We may want to re-base this to use the python3.8 update once that's merged to main.

**Comment by canwaf** [comment]
Hey @rossbowen, I think this should be reopened, as a link back from #138, and the replacement for the table loader https://github.com/GSS-Cogs/databaker/issues/8. How do we want to track this?

**Comment by rossbowen** [comment]
Sorry @canwaf! Let's reopen if this isn't actually complete and track progress against Pandas V1 here, which naturally links to #138.

**Comment by mikeAdamss** [comment]
this will be nasty ..but.. should be doable once Charles' pr's are in. Looking to do it Sprint 36.

**Comment by mikeAdamss** [comment]
blocked until this is done: https://github.com/GSS-Cogs/gss-utils/issues/233
