### ISSUE TITLE
NHS Digital scraper failing

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#5]
The NHS-Statistics-on-Alcohol-England pipeline is failing because the NHS Digital scraper is throwing an exception.

See https://ci.floop.org.uk/job/GSS_data/job/Health/job/NHS-Statistics-on-Alcohol-England/52/console

**Comment by mikeAdamss** [comment]
we had a look at this but it's been de-prioritsed for DE's as it appears to be a bit more more work than a quick fix.

it appears to have previously scraped the distribution level info from a splash page of sorts. That distribution level of info appears to have been removed, so (I think) it’ll now need to

* get all the dataset_links from the splash page
* follow each dataset_link
* create a distribution for each distribution_link within each dataset_link

**Comment by ajtucker** [comment]
The scraper was doing this already. One issue was that it wasn't properly parsing dates, but that was fixed in 8a93ef2e07f7d63900f6631dffb2458d61ed458e.
