### ISSUE TITLE
Tracing - todo, breaking scenarios, issues encountered etc

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/gss-utils#56]
If you find a new scenario I didn't account for then just add it to this issue please. A code snippet if you have one would be grand as well.

**Comment by mikeAdamss** [comment]
Column labels with hyphens in the name fail when being set to attribute.

eg ```
columns=["My-dimension"]
trace.start("a dataset", tab, columns, link)
```

will break as `trace.My-Dimension` is not a viable attribute name. 

need to add a replace.("-", "_") here: https://github.com/GSS-Cogs/gss-utils/blob/d6597626ddf5057d7cfabee52b5337dea16505b7/gssutils/tracing/transform.py#L31

**Comment by RedWalters** [comment]
Column labels which start with numbers cannot be used as Python cannot create attributes which start with numbers

eg 

```
columns=["95 Interval"]
trace.start("a dataset", tab, columns, link)
```

cannot work as when you try to add a comment:

`trace.95_Interval("Something ") `

```
  File "", line 28
    trace.95_interval('')
            ^
SyntaxError: invalid token
```

Computer says no.

The only real solution I can think to this would be to remove all numbers when creating the attribute and have a warning pop up informing the user of the change and what the attribute now looks like.

**Comment by RedWalters** [comment]
Found a small bug that may or may not be able to be addressed. 

If a "NoLookupError" is thrown when building the dimensions in databaker causing the script to fail it seems to lock up the trace program while its attempting to build the html preview. This causes a PermissionError when the issue causing the NoLookupError is fixed and seemingly can only be resolved by Restarting the Jupyter Kernel.

I can most easily recreate this error when incorrectly defining the observation dimension, getting the NoLookupError, fixing the Observation Dimension and then running the script again which results in this error:

```
PermissionError                           Traceback (most recent call last)
 in 
----> 1 trace = TransformTrace()
      2 
      3 tabs = { tab: tab for tab in distribution.as_databaker() }
      4 
      5 tidied_sheets = []

~\anaconda3\lib\site-packages\gssutils\tracing\transform.py in __init__(self)
     66         # Remove any lingering documentation from the last run
     67         if os.path.exists("documentation"):
---> 68             shutil.rmtree("documentation")
     69 
     70     def _set_composite_key(self, cube_name, tab_name, source):

~\anaconda3\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    514             # can't continue even if onerror hook returns
    515             return
--> 516         return _rmtree_unsafe(path, onerror)
    517 
    518 # Allow introspection of whether or not the hardening against symlink

~\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    393                 onerror(os.path.islink, fullname, sys.exc_info())
    394                 continue
--> 395             _rmtree_unsafe(fullname, onerror)
    396         else:
    397             try:

~\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    398                 os.unlink(fullname)
    399             except OSError:
--> 400                 onerror(os.unlink, fullname, sys.exc_info())
    401     try:
    402         os.rmdir(path)

~\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    396         else:
    397             try:
--> 398                 os.unlink(fullname)
    399             except OSError:
    400                 onerror(os.unlink, fullname, sys.exc_info())

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'documentation\\previews\\b7e54ab0-da77-4578-ab02-9ee6f3ed4f6e.html'
```

**Comment by mikeAdamss** [comment]
@RedWalters - really interesting one, its because ConversionSegment() doesent actually process the data until the last possible moment to allow for interventions (sadly in this scenario the last possible moment is while we're also trying to shove the data into some javascript, so things get .. .messy).

You can force the processing whenever you want though, via `cs.process()`, so we need to add that force inside a try catch - inside `trace.preview()` but before it calls savepreviewhtml`, that should avoid any future gumming up of things.

**Comment by mikeAdamss** [comment]
**Seperate html from data**.

Currently we're writing the json, then re_iteratimg that same data and hard coding it into a html file.

Should really just be a standard javascrpt/d3 file thing happens to use the json.

Something styled a bit less 90's while we're in there wont hurt either.

**Comment by mikeAdamss** [comment]
closing this, its outdated.
