### ISSUE TITLE
Spatiotemporal coverage & resolution

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#78]
When the Scraper is constructed from a seed `info.json` file, use any spatiotemporal coverage and resolution properties if available to populate the corresponding DCAT properties of the dataset metadata.

Depends on coining a new property for spatial resolution that can point to a URI denoting some level in a geographic hierarchy.

**Comment by rossbowen** [comment]
Closing as tracking elsewhere.
