### ISSUE TITLE
ONS Scraper KeyError: 'description'

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#82]
As noted by Rob in GSS-Cogs/family-covid-19#177, the ONS Scraper has been throwing exceptions recently, perhaps due to changes in the ONS `/data` endpoint?

**Comment by ajtucker** [comment]
Added an issue branch for this: https://github.com/GSS-Cogs/gss-utils/tree/issue-82

Added a minimal, failing test for debugging.

**Comment by mikeAdamss** [comment]
Discussed with AJay and Alex. This is not really a key error, the scraper is being used on the wrong type of page, updated task is:

* when scraping a /data endpoint, check the "type" field, throw an exception if it's not on an accepted type list.
* for now the only accepted type should be `dataset_landing_page` but still make it a list as there will be others.
* add bdd tests, at least 1 for correct page type and 1 for incorrect page type.

**Comment by mikeAdamss** [comment]
this is the correct landingPage: https://www.ons.gov.uk/peoplepopulationandcommunity/wellbeing/datasets/coronaviruspersonalandeconomicwellbeingimpacts
