### ISSUE TITLE
rdfs:comment and dct:description

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/gss-utils#85]
The [metadata documentation for PMD](https://github.com/Swirrl/cogs-issues/wiki/PMD4-metadata/_compare/8af17d9d31c9d32176b4180e211b34a558c2b494...3465931d4b1f01a3b1e1f714acaefd051a53a478) has been updated to make clear how `rdfs:comment` and `dct:description` are used in the user interface.

The scrapers need to be updated with this in mind.

**Comment by rossbowen** [comment]
[UK Sea Fisheries Statistics](https://staging.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Fcovid-19%2Fmmo-ad-hoc-statistical-release-uk-sea-fisheries-statistics-catalog-entry) has:

```ttl
<http://gss-data.org.uk/data/gss_data/covid-19/mmo-ad-hoc-statistical-release-uk-sea-fisheries-statistics-catalog-entry>
    a <http://publishmydata.com/pmdcat#Dataset>;
    dcterms:description """Published in response to the COVID-19 pandemic to provide timely evidence on impacts on commercial sea fishing activity"""@en;
    rdfs:comment "Volume landed of the UK fishing fleet by country, vessel length and species group, November"@en;
```

I don't see `dcterms:description` used anywhere on PMD. `rdfs:comment` is used within the catalog and cube explore pages. The wiki talks about `pmdcat:markdownDescription` being available.
> ```pmdcat:markdownDescription # a longer description of the dataset for the About tab. Can contain markdown. If so, should have a datatype of <https://www.w3.org/ns/iana/media-types/text/markdown#Resource>.```

Having a quick look at https://www.gov.uk/government/statistics/final-uk-greenhouse-gas-emissions-national-statistics-1990-to-2019:

```python
#%%
import requests

x = (requests.get(
        f'https://www.gov.uk/api/content/government/statistics/final-uk-greenhouse-gas-emissions-national-statistics-1990-to-2019'
        ).json()
)
```

Yields:

```python
#%%
x["description"]

#> 'Final estimates of UK territorial greenhouse gas emissions.'

#%%
x["details"]["body"]

#> '<div class="govspeak"><p>This publication provides the final estimates of UK territorial greenhouse gas emissions going back to 1990.</p>\n\n<p>Estimates are presented by source in February of each year. They are updated each year:</p>\n\n<ul>\n  <li>in March, to include estimates by end-user and fuel type</li>\n  <li>in June, to include estimates by Standard Industrial Classification (<abbr title="Standard Industrial Classification">SIC</abbr>)</li>\n</ul>\n\n<p>The statistics covers emissions that occur within the UK’s borders. When emissions are reported by source, emissions are attributed to the sector that emits them directly. When emissions are reported by end-user, energy supply emissions by source are reallocated in accordance with where the end-use activity occurred. This reallocation of emissions is based on a modelling process. For example, all the carbon dioxide produced by a power station is allocated to the power station when reporting on a source basis. However, when applying the end-user method, these emissions are reallocated to the users of this electricity, such as domestic homes or large industrial users.</p>\n\n<p>BEIS does not estimate emissions outside the UK associated with UK consumption, however the Department for Environment, Food and Rural Affairs publishes estimates of the <a href="https://www.gov.uk/government/statistics/uks-carbon-footprint" class="govuk-link">UK’s carbon footprint</a> annually. The <a href="https://www.gov.uk/government/publications/uk-greenhouse-gas-emissions-explanatory-notes" class="govuk-link">alternative approaches to reporting UK greenhouse gas emissions report</a> outlines the differences between them.</p>\n\n<p>For the purposes of reporting, greenhouse gas emissions are allocated into a small number of broad, high level sectors known as National Communication sectors, which are as follows: energy supply, business, transport, public, residential, agriculture, industrial processes, land use land use change and forestry (<abbr title="land use land use change and forestry">LULUCF</abbr>), and waste management.</p>\n\n<p>These high-level sectors are made up of a number of more detailed sectors, which follow the definitions set out by the <a rel="external" href="http://www.ipcc.ch/" class="govuk-link">International Panel on Climate Change (<abbr title="International Panel on Climate Change">IPCC</abbr>)</a>, and which are used in international reporting tables which are submitted to the <a rel="external" href="https://unfccc.int/" class="govuk-link">United Nations Framework Convention on Climate Change (<abbr title="United Nations Framework Convention on Climate Change">UNFCCC</abbr>)</a> every year. A <a href="https://www.gov.uk/government/publications/uk-greenhouse-gas-emissions-explanatory-notes" class="govuk-link">list of corresponding Global Warming Potentials (<abbr title="Global Warming Potentials">GWPs</abbr>) used and a record of base year emissions</a> are published separately.</p>\n\n<p>This is a National Statistics publication and complies with the Code of Practice for Statistics.</p>\n\n<p>Please check our <a href="https://www.gov.uk/government/publications/uk-greenhouse-gas-emissions-statistics-user-guidance" class="govuk-link">frequently asked questions</a> or email <a href="mailto:Climatechange.Statistics@beis.gov.uk" class="govuk-link">Climatechange.Statistics@beis.gov.uk</a> if you have any questions or comments about the information on this page.</p>\n\n</div>'
````

I don't know if these are consistent across other GOV UK pages, but I suppose these could be mapped to `rdfs:comment` and `pmdcat:markdownDescription` respectively after a bit of cleansing?

**Comment by ajtucker** [comment]
Yeah, https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/scrapers/govuk.py tries to cope with the various ways that folks are using and abusing the content API. It doesn't help that some of the useful metadata about e.g. files/resources/distributions is only available by parsing the HTML in the strings in the JSON response. This may have changed, so we should check.

For `dct:description`, we had some back and forth about whether PMD could accept a datatype literal for this (i.e. typing the string as Markdown using `https://www.w3.org/ns/iana/media-types/text/markdown#Resource`), given that lots of folks will use Dublin Core properties as per https://www.w3.org/TR/vocab-dcat-2/#Property:resource_description

The upshot was that Swirrl argued for a different/bespoke property as you noted, partly as it's easier to query/filter. I still contend that we need to ensure that PMD can make use of the properties recommended in DCAT.

We do already convert some HTML to Markdown in the various scrapers using https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/scrape.py#L137 which uses https://pypi.org/project/html2text/. See e.g. https://github.com/GSS-Cogs/gss-utils/search?q=to_markdown

What we could do with is setting up some test cases in e.g. https://github.com/GSS-Cogs/gss-utils/blob/master/features/pmd.feature to check that we're getting things in the right place.

**Comment by rossbowen** [comment]
So given greenhouse gases above, do we want the output to be:

```ttl
<http://gss-data.org.uk/data/gss_data/climate-change/final-uk-greenhouse-gas-emissions-national-statistics-1990-to-2019>
    a <http://publishmydata.com/pmdcat#Dataset>;
    rdfs:label "Final estimates of UK territorial greenhouse gas emissions."@en
    dcterms:description "This publication provides the final estimates of UK territorial..."^^<https://www.w3.org/ns/iana/media-types/text/markdown#Resource>
```

and open an additional issue for Swirrl to swap `pmdcat:markdownDescription` to `dcterms:description`?

**Comment by ajtucker** [comment]
I'd open the issue about `pmdcat:markdownDescription` but punt it to the broader Epic about document types, templates and properties GSS-Cogs/sprint-planning#33.

**Comment by canwaf** [comment]
Markdown description will be supported when csvcubed 0.1.2 is released. Summary and description distinction captured in csvcubed.
